class DatabaseAlreadyOpenedException implements Exception{}
class UnableToGetDocumentsDirectory implements Exception{}
class DatabaseNotOpenException implements Exception{}
class CouldNotDeleteUserException implements Exception{}
class UserAlreadyExistsException implements Exception{}
class UserNotExistException implements Exception{}
class CouldNotDeleteNoteException implements Exception{}
class CouldNotFindNoteException implements Exception{}
class CouldNotUpdateNoteException implements Exception{}
class UserShouldBeSetBeforeReadingAllNotesException implements Exception{}